gleitz/howdoi

setup.py
=> E231 && E301 PEP8 fix

howdoi/howdoi.py
- Private functions named properly
- `sys.version` is used explicitly instead of  `ImportError` (`Explicit is better than implicit`) :grinning: 
- Line length made <= 120 char
=> PEP 8 conventions

howdoi/howdoi.py, test_howdoi.py
I was going through the code and found that is question was getting checked in the method giving links at position, so i moved it outside, do you think the same or there is something i am missing ? I will change the tests later, but first want to confirm with my thought.
=> _is_question logic check is moved outside

test_howdoi.py
seems that https is now being returned - this will handle both http and https results in the future
=> fix http(s) errors in test_all_text, test_answer_links

README.rst
- change inline code formatting from ` to ``
- small typo: my -> may -> might
=> Format README.rst Development section to ReST

howdoi/howdoi.py, test_howdoi.py
This is my attempt to resolve Issue #152, using PR #153 as a starting point. I fixed the merge conflict that prevented merger while also adding in the ★ character as suggested by [GabeLeRoux]( https://github.com/gleitz/howdoi/pull/153#issuecomment-244577201). Let me know if you like it!
=> Add links, with ★ characters to separate the link from the content

howdoi.rb
i assume it'd also work with regular homebrew... but couldn't test that :thinking: 
would you want to keep maintaining it here, or turn it over to the homebrew repo? 
(or is it already maintained in a different tap somewhere that slipped under my radar?)
=> update formula to work with linuxbrew

README.rst, howdoi/howdoi.py
added a bing arg to the cmdline interface so HOWDOI_SEARCH_ENGINE can be set within the howdoi process itself.
=> More granular control over HOWDOI_SEARCH_ENGINE

MANIFEST.in
Also explicitly include & exclude other files
as needed to satisfy check-manifest.
=> MANIFEST.in: Include tests

.gitattributes
Addresses #296.
Don't think the linguist will kick in right away. If this doesn't update the repo to be Python after a bit of time, I'll investigate further. 👍
=> Fix main repository language

howdoi/howdoi.py
when users run `python -m howdoi.howdoi -C how do I print helloworld in python`, howdoi would return `Cache cleared successfully` and therefore ignoring the query. 
This PR fixes that.
=> Cache query fix

howdoi/howdoi.py, test_howdoi.py
Fixes: #310 
This issue is because `stackoverflow` have change the answer node relative `class`.  And we can't find `.post-text` anymore.
=> fit new stackoverflow css class

howdoi/howdoi.py, test_howdoi.py
e.g. `-n -1`, `-p -2`, `-p 40`, `-n 35`
Also added tests
=> Add a range checker for all int fields (max is now 20 answers)

requirements.txt, requirements/common.txt, requirements/dev.txt, requirements/prod.txt
- This PR fixes issue #293 by adding a requirements folder that contains three different .txt files for common/development/production specific requirements.
=> Requirement Files 

.github/workflows/python-non-master.yml, .github/workflows/python.yml, .gitignore, howdoi/howdoi.py, requirements/common.txt, setup.py, test_howdoi.py
Made migration from os.path to pathlib.Path
changes are in `setup.py` and `test_howdoi.py` files
=> Update to pathlib

howdoi/howdoi.py
refer - https://meta.stackexchange.com/questions/108949/question-url-slugs-based-on-title
=> fix: make regex pattern more specific to avoid incorrect link matches

.github/workflows/early-warning.yml
Implements an early warning CI as discussed in #337 
The remaining features discussed in the issue are based on the previous scraping approach and might not be relevant now, so this might close #337
=> add early warning system CI

howdoi/howdoi.py
Parallelizes page queries according to #354
=> Parallelize page fetch queries

howdoi/howdoi.py
Closes #355 
Just FYI - adding inspect calls seem to slow cached queries down by 10ms on my local machine
=> Cache patch

howdoi/howdoi.py
=> Keep checking remaining engines if some engine fails 

docs/index.md, docs/user-guide.md, howdoi/errors.py, howdoi/howdoi.py
Add explainability and update logging
Fixes https://github.com/gleitz/howdoi/issues/334
Fixes https://github.com/gleitz/howdoi/issues/330
=> Explainability (v2)

notebooks/language_labelling.ipynb
Dump of the NLP notebook so far.
=> feat: add language labelling notebook so far

.github/ISSUE_TEMPLATE/bug-report.md
=> feat: add bug report issue template to encourage users to use --explain

docs/windows-contributing.md, mkdocs.yml
Added markdown file for documentation of Windows development. Updated mkdocs.yml file to contain a link to that. 
Issue: 
When I run the `mkdocs build` command, a new folder containing the source code for the site is created in the docs branch. `mkdocs serve` hosts it locally and shows that the site is working. Problem is that this folder is different from the already created folders on gh-pages branch, neither does it show the changes on the documentation site. Would appreciate help with this, thanks :)
=> Docs updated

.github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/help-and-asking-questions.md, .github/ISSUE_TEMPLATE/miscellaneous.md
To help people have an outline for creating issues, issue templates were added
=> added templates for issues

README.rst, howdoi/howdoi.py
Updated Readme for moving all of the important documentation to mkdocs
=> Updated Readme

README.rst, docs/usage.md, howdoi/howdoi.py
Hi, I think present tense should be used (use 'display' to replace 'displays') for consistency.
=> Corrected Verb Tense Error

howdoi/howdoi.py
* fix "total answers" logging message counting empty results
* return False from `_get_answers` if the only results had no answer
=> filter empty results from answers

howdoi/howdoi.py, requirements/common.txt, setup.py, test_howdoi.py
A fork of https://github.com/gleitz/howdoi/pull/443 to address failing tests.
cc @V2dha
=> Syntax highlighting using rich library

howdoi/howdoi.py, requirements/common.txt, setup.py
Fixes https://github.com/gleitz/howdoi/issues/445
=> Use `colorama` to support colorization in Powershell

howdoi/howdoi.py, test_howdoi.py
- Links to issues solved
#466 
- Refactoring
Please provide detailed instructions for testing your changes locally, including expected response/behavior.
If there are bugs in your current changes you can still open the PR and mention the bugs you found. Propose further changes that can help fix bugs in your current changes.
=> Refact: move function to adequate file

requirements/common.txt, requirements/dev.txt, setup.py, test_howdoi.py
Update dependencies to fix failing build that was discovered in https://github.com/gleitz/howdoi/pull/467.
- Bug fixes
=> Update dependencies to fix github pipeline

README.md
Fix homepage image
- Bug fixes (UI)
=> Fix homepage image

.github/workflows/docs.yml, .github/workflows/early-warning.yml, .github/workflows/python-non-master.yml, .github/workflows/python.yml, .pre-commit-config.yaml, .pylintrc, requirements/dev.txt, setup.py, test_howdoi.py
Adding support for Python 3.11
- New feature
=> Add Python 3.11 support
