.gitignore
howdoi/howdoi.py

The main culprit seemed to be the import of `TerminalFormatter`, as it's in `pygments.formatters.terminal`, not `pgyments.formatters`. So, after changing that import, the issues in #134 behind automatic colorization via the `HOWDOI_COLORIZE` environment variable seem to have been fixed.
I also added some stuff to the `.gitignore` file (mostly via [gitignore.io](https://www.gitignore.io/)) to make the ignoring a little more robust. I needed to add at least *something*, since I was using PyCharm.

Fixed broken import and made .gitignore more robust

---

howdoi/howdoi.py

requests now rightly screams for the lack of security but HTTP request didn't have any to begin with.
➜  ~ howdoi bake cake     
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
cake bake model all
ref issue:
#144

ignoring ssl certificate when HOWDOI_DISABLE_SSL is set

---

howdoi/howdoi.py
test_howdoi.py

Also added an automated test to check if _get_questions is working.
Ensured that this automated test works on Python 2.6 as well.
Issue was originally reported in #175, and fixed in #176, but a problem with rebasing forced me to abandon the PR and start a new "clean" PR. This time, everything's good to go. 👍

Fix issue where the wrong answer url was being displayed to the user

---

howdoi/howdoi.py

Fixes an issue found with #169.

Fix UTF-8 in Python 3 when terminal encoding is ASCII

---

README.rst
howdoi/howdoi.py

Sadly found that howdoi doesn't work for me, after hacking into the code, I found that howdoi use *Google* to search for relative links of *StackOverflow*, but *Google* search engine doesn't support for my country :(
So I would like to add support for *Bing* search engine.  To make it work in my environment.
When user input command like this:
howdoi usage of tar -b
Howdoi will use bing search engine to find stackoverflow links, and then user can get the result here :)
Consider for add an argument rather than use environment variable:
I think that use argument for bing searching can make user easily select when to use bing or google, if using environment variable, it's a little more complicated.
And by the way, I have add 2 blank line to make our code more fitted with pep8

Add support for bing search engine

---

howdoi/howdoi.py

I found that when I'm trying to use howdoi like this:
```
howdoi python asyncio sample -n 4 
```
which takes me a little long time to get the response.  So I'm trying to make it to be more efficient when howdoi try to fetch more than one answers.  Which use `get` method defined in ``` requests Session ``` object instead of using ``` requests.get ``` function to fetch page.
The benefit of using session is showed here:
http://docs.python-requests.org/en/master/user/advanced/ 
There are another way to rewrite this like using python3 *asyncio* library, to make all these fetch action *asynchronous*.  But each running of howdoi will not make very large connections, and so the benefit of using *asyncio* library is not so obvious.  And using *asyncio* library will break *python2* support...
Here …

use requests session to improve performance for querying more than 1 answer

---

howdoi/howdoi.py

Hi, I found that *howdoi* shows a little unfriendly when we are try to query for more than one answers, when we Read *howdoi* output, it's a little hard to figure out where is the answer 1st, where is the answer 2nd immediately (it's especially when we read the output from console).
So I would like to add spliters (using '=') between answers.  Of cause it's not so necessary for the howdoi main feature...
**Before adding split line between answer**:
```
★  Answer from https://stackoverflow.com/questions/37329392/does-a-long-running-loop-with-async-io-needs-the-longrunning-option ★
Short answer, no. For background reading try http://blog.stephencleary.com/2013/11/there-is-no-thread.html
Also, you do not need the await Task.Delay at the end to give time for other work in an async-await …
```

add '=' split string between answers to make the result shows more friendly

---

test_howdoi.py

When writing automated tests for #177, I learned that
Python 2.6 did not have support for assertSequenceEqual. To ensure
that the automated tests could run on Python 2.6, I wrote some
additional code.
However, in #186, we dropped support for Python 2.6. Therefore,
we no longer need this code. Removing it would help simplify
the test code and make it easier to maintain.

Remove unnecessary test code that supported Python 2.6

---

howdoi.rb

Was able to replicate issue #192 and figured out how to fix that issue by simply updating the PyQuery dependency from 1.2.11 to 1.4.0. I found the download link from [here](https://pypi.org/project/pyquery/1.4.0/#files), which is the closest you can get to an official endorsement from pypi.org itself (even though the download itself is hosted at https://files.pythonhosted.org).
After updating the dependency, I was able to install howdoi using homebrew.

Update pyquery dependency

---

howdoi/howdoi.py
test_howdoi.py

From the commit message:
>Some answers on the StackExchange network include hyperlinks
to other content on the Internet. Ideally, those hyperlinks would serve
as "supplemental" reading, but there has been instances where the hyperlink
contains most of the answer (the so-called "link-only answers").
>howdoi currently ignores all hyperlinks within the answer of the
question, preferring instead to display a raw-text version of the answer.
While this is suitable for most instances, there are a few cases
where you may want to dig deeper and follow those hyperlinks, especially
if you have encountered a "link-only answer". Rather than viewing the
StackExchange answer through the browser and risk distraction,
it would be preferable to see the hyperlinks directly in the terminal.
In the future, I …

Display links using markdown syntax

---

howdoi/howdoi.py
requirements.txt

Pygments is notorious for slow imports. Load it lazily = win.

Lazily load pygments to cut start-up time significantly

---

MANIFEST.in
fastentrypoints.py
howdoi/howdoi.py
setup.py

This is some dark magic (well, greyish) to make the launch script generated by setuptools as fast as the one generated when installing a wheel. Makes for 200+ms speed-up (about 50%) on my box. Even bigger for python2. See #230 
I would have preferred to include fastentrypoints as a submodule, but the way that repo is structured it's not worth it for the added complexity. Including it as a requirement would be equally problematic. It is intended to be vendored according to the authors, so that's what we're doing here.

Speed up setuptools-installed howdoi by ~50%

---

howdoi/howdoi.py
requirements.txt
setup.py

See #224 for overall discussion.
Additional changes not mentioned there:
* Use appdirs to find cache directory less kludgily, should now work on Windows as a by-product (not tested though, don't have a Windows machine)
* Remove import random and use a simple internal randomizer based on os.urandom to select User-Agent
Still to come:
* Second-level cache so we don't have to hit upstream again when user wants full answer, second answer, different colorization setting etc

Replace requests_cache with a light, filesystem-based cache

---

howdoi/howdoi.py

In my country Google adds a "Translate site" link to most of the results in foreign languages, which breaks howdoi. The `hl` parameter fixes the issue without breaking other search engines, including Bing.

Explicitly set English interface in SEARCH_URLS

---

README.rst
howdoi/howdoi.py
test_howdoi.py

`howdoi.howdoi` accepts both parsed and raw queries to be passed directly to it. So the following snippet:
```python
from howdoi import howdoi
query = "for loop python"
parser = howdoi.get_parser()
args = vars(parser.parse_args(query.split(' ')))
output = howdoi.howdoi(args)
```
Can **also** be written as:
```python
from howdoi import howdoi
query = "for loop python"
output = howdoi.howdoi(query)
```
This doesn't break compatibility with the previous version.

Add flexible raw query argument to howdoi.howdoi

---

test_howdoi.py

@gleitz This replaces the teardown method with deleting the keys from the os.environ object. it's important to check if the key exists before attempting to delete because the env variable may not be set.

Change test teardown methods

---

howdoi/howdoi.py

Addresses #297.
Simple check to see if a `FileNotFoundError` exception would be thrown or not. If thrown, we know the user did not initialize `.keep/` so we run `keep init` to initialize the environment for them. After we do this, we save their query.
If a `FileNotFoundError` exception is not thrown, then we're good to go.

Fixed keep initialization

---

.github/workflows/docs.yml
.gitignore
docs/contributing.md
docs/index.md
docs/installation.md
docs/troubleshooting.md
docs/user-guide.md
mkdocs.yml

I added the basic MKDocs setup files along with some examples of the features you can use like tooltips, code blocks etc. This isn't meant to be a finished product it's mainly a preview as to what MKDocs looks like and how to use the various features and extensions that it has.
The commands you need to use it are
`pip install mkdocs-material markdown-include`
and
`python -m mkdocs serve` - Start the live-reloading docs server.
`python -m mkdocs build` - Build the documentation site.
`python -m mkdocs help` - Print this help message
At the moment there is no live buiilding and serving of the docs on commits as there would be with the github actions setup for it. I took some inspiration from [Typer's](https://github.com/tiangolo/typer) use of MKDocs so if you'd like to get that setup it'd …

MKdocs setup

---

howdoi/howdoi.py

Switch to regex to avoid breakage every time XPATH of query results is slightly altered. Should fix #339 #338 #332 etc
Fetches links in order and works on all the examples I've tried.

switch to regex for extracting links for google query

---

howdoi/howdoi.py

Make link extraction regex for Google extract only stackoverflow links from page, as opposed to all links

fix: make google query extract only stackoverflow links from page

---

howdoi/errors.py
howdoi/howdoi.py

Adds a `--sanity-check` flag to howdoi that checks if a standard query ("format date bash") works or fails on all currently supported engines. 
Implements the first feature in the checklist at #337

add sanity check

---

howdoi/howdoi.py

on connection exception, return dict instead of set.
close #363

fix bug in howdoi() function

---

howdoi/howdoi.py

to avoid redirection failing sometimes.
close #368

use duckduckgo no-javascript version directly

---

howdoi/howdoi.py

complements BLOCK_INDICATORS.
close #367

check for HTTP errors (ex. 403), to better detect when a server is blocking us

---

howdoi/howdoi.py

This allows you to make queries like
```
HOWDOI_URL=cooking.stackexchange.com howdoi make pizza
```

For Google URL matches, use the `HOWDOI_URL`

---

howdoi/howdoi.py

The only problem for European users was the GDPR splash screen that Google was showing. Adding a small cookie jar onto our request may fix all of that. Seems to work for me.

GDPR fix for Google?

---

.pre-commit-config.yaml
requirements/dev.txt
setup.py

I have added both `lint` command and pre-commit hook, in case someboady wants to run `python setup.py lint` manually without adding the modified files to staging area.
Also for the command, currently I have added basic messages for the case when no linting errors are found and for the case when `flake8` is not installed. Any suggestions for improving these messages would be very helpful.

Added Lint command and pre-commit hook

---

howdoi/howdoi.py
test_howdoi.py

Fixes the problem of not respecting HOWDOI_SEARCH_ENGINE environment variable, issue [#377](https://github.com/gleitz/howdoi/issues/377)
1.   `--engine` will be preferred over the env variable
2. In case google is one of the conflicting choices, the non-google search engine will be preferred, wherever it is specified, in the env variable or with `--engine`
Kindly review and let me know if any changes are needed.

os.environ['HOWDOI_SEARCH_ENGINE'] FIX

---

howdoi/howdoi.py
test_howdoi.py

Addresses issue #407 . 
Fallbacks in case of search engine failure: iterates through the supported engines to find a search engine that has not been blocked. If all supported engines are blocked, it simply returns.

Search engine fallbacks - including test 

---

howdoi/howdoi.py

Closes #420 
Works around cachelib throwing a FileNotFoundError on cache misses. Updating to the latest version of cachelib did not seem to resolve the issue, so this seems to be the best solution for now.

Workaround FileNotFoundError thrown by cachelib

---

howdoi/howdoi.py

This PR is related to #426 
- removed if statement for checking python version
- removed utf-8 encoding
close #426

Drop python2 support in command_line_runner

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docs.yml
.github/workflows/early-warning.yml
.github/workflows/python-non-master.yml
.github/workflows/python.yml
requirements/common.txt
requirements/dev.txt
setup.py

Fixes https://github.com/gleitz/howdoi/issues/447
Also include Python 3.10 as the default and supported version.
Also update `nose` to `nose2` to handle an issue with Python 3.10. Perhaps We should switch to Pytest in the future.

Perhaps we do not need pathlib for Python 3.4+

---

howdoi/howdoi.py

- Tasks solved
Errors reported when run:
howdoi --num-answers 2 python lambda function list comprehension
```
File "/home/dizzygz/myprog/python/howdoi/howdoi/howdoi.py", line 468, in _get_answer_worker
multiple_answers = (args['num_answers'] > 1 or args['all'])
TypeError: '>' not supported between instances of 'str' and 'int'
File "/home/dizzygz/myprog/python/howdoi/howdoi/howdoi.py", line 437, in _get_answers
final_pos = initial_pos + args['num_answers']
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
- Links to issues solved
- Bug fixes
- New feature
- Improvement
- Refactoring
- Documentation update
- Security fix
Please provide detailed instructions for testing your changes locally, including expected response/behavior.
If there are bugs in your current changes you …

update 2 places for int and str operations

---

test_howdoi.py

- Tasks solved
One bad test case `query_without_code_or_pre_block` where it is comparing hardcoded string into howdoi search result which can be changing anytime.
Please check @gleitz 
- Test fix
Please provide detailed instructions for testing your changes locally, including expected response/behavior.
If there are bugs in your current changes you can still open the PR and mention the bugs you found. Propose further changes that can help fix bugs in your current changes.

fix: remove bad test case

---

docs/howdoi_advanced_usage.md

Fixed a doc by adding a missing line break
- Documentation update
N/A
I don't think any of the unchecked steps are applicable.
None

add missing line break to doc
